#!/bin/sh
webpack --devtool source-map

node_modules/.bin/uglifyjs dist/example.js \
  --output dist/example.min.js \
  --source-map dist/example.min.map \
  --source-map-url example.min.map \
  --compress warnings=false